### ISSUE TITLE
Pose Permission Issue

### ISSUE THREAD

**Issue by AlohaLegend** [KessPenGames/SimpleArmorStandPose#1]
Hello there! A few thing in this one. Wanted to say this is a great plugin, thank you for developing. I am currently having one issue and I have one feature request. Basically my issue is in regards to perms. At the current moment I have permission enabled. But if a player doesn't have the permission to change the armor stand pose, they cant use an armor stand. Cant add armor or take armor off. So the perm basically restricts player from using armor stands all together. 

And as for the feature request, Would it be possible to somehow allow bedrock players to adjust armor stands? Currently if they try to change the position of stand it just breaks the stand. We have tried crouch clicking the stand using a bedrock account through geyser. 

Thanks in advance.

**Comment by KessPenGames** [comment]
Hello, I can’t say anything about the bedrock players, concerning the bug, everything will be fixed, I will try to fix it as soon as possible.

**Comment by CubBossa** [comment]
The permission issue might be closed with #2, i changed the order of checks in the listener. Permissions are then only checked if the player is sneaking, which allows them to change armorstand armor and stuff as long as they're not

**Comment by KessPenGames** [comment]
Fixed in version 2.1
